### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by xakepnz** [xakepnz/STRIKEWRITER#1]
https://github.com/xakepnz/STRIKEWRITER/blob/ba393c3ba34868de187be7b5a0d2b303574ac1d5/strikewriter#L23

**Comment by xakepnz** [comment]
**Tried IP**: 139.162.13.242

When it hit the json load from the virustotal results:

```
Traceback (most recent call last):
  File "./strikewriter", line 254, in <module>
    main()
  File "./strikewriter", line 240, in main
    vt(ip)
  File "./strikewriter", line 23, in vt
    binoutv = json.loads(binaryv)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by xakepnz** [comment]
Full output from script: - Doesn't seem to be alerting.
```
xakep@gcsb:~$ ./scripts/STRIKEWRITER/strikewriter -i 139.162.13.242
 
   /######  /######## /#######  /###### /##   /## /######## 
   /##__  ##|__  ##__/| ##__  ##|_  ##_/| ##  /##/| ##_____/ 
  | ##  \__/   | ##   | ##  \ ##  | ##  | ## /##/ | ##       
  |  ######    | ##   | #######/  | ##  | #####/  | #####    
   \____  ##   | ##   | ##__  ##  | ##  | ##  ##  | ##__/    
   /##  \ ##   | ##   | ##  \ ##  | ##  | ##\  ## | ##       
  |  ######/   | ##   | ##  | ## /######| ## \  ##| ######## 
   \______/    |__/   |__/  |__/|______/|__/  \__/|________/

   /##      /## /#######  /###### /######## /######## /####### 
  | ##  /# | ##| ##__  ##|_  ##_/|__  ##__/| ##_____/| ##__  ## 
  | ## /###| ##| ##  \ ##  | ##     | ##   | ##      | ##  \ ## 
  | ##/## ## ##| #######/  | ##     | ##   | #####   | #######/ 
  | ####_  ####| ##__  ##  | ##     | ##   | ##__/   | ##__  ## 
  | ###/ \  ###| ##  \ ##  | ##     | ##   | ##      | ##  \ ## 
  | ##/   \  ##| ##  | ## /######   | ##   | ########| ##  | ## 
  |__/     \__/|__/  |__/|______/   |__/   |________/|__/  |__/

         Link: https://github.com/xakepnz/STRIKEWRITER 
  ------------------------------------------------------------- 
 
[*] IP Information:

 [+] IP: 139.162.13.242
 [+] Hostname: ns2.sg2.fcomet.com
 [+] Provider: AS63949 Linode, LLC
 [+] Country: SG
 
[*] Threat Information:

 [+] AbuseIPDB: No Results. 
 [+] Ransomware Tracker: No Results. 
 
[+] Cymon: Found! 
 [+] - Link: https://cymon.io/139.162.13.242

 
 [+] Threatcrowd: Found! 
  [+]  - Link: https://www.threatcrowd.org/ip.php?ip=139.162.13.242

 [+] Feodo Botnet Tracker: Not found. 
 [+] Virustotal: Not found. 
```
